[2024-07-12T18:31:26.134+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:31:26.137+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:31:26.138+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-12T18:31:26.142+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-07-11 00:00:00+00:00
[2024-07-12T18:31:26.144+0000] {standard_task_runner.py:57} INFO - Started process 55 to run task
[2024-07-12T18:31:26.146+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpiy_g227c']
[2024-07-12T18:31:26.147+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask s3_upload
[2024-07-12T18:31:26.163+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [running]> on host d7a6ef074cc8
[2024-07-12T18:31:26.190+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T18:31:26.508+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-07-12T18:31:26.510+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-07-12T18:31:26.522+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20240711T000000, start_date=20240712T183126, end_date=20240712T183126
[2024-07-12T18:31:26.533+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task s3_upload ('NoneType' object has no attribute 'split'; 55)
[2024-07-12T18:31:26.549+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-12T18:31:26.560+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T18:35:03.275+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:35:03.279+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:35:03.279+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-12T18:35:03.284+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-07-11 00:00:00+00:00
[2024-07-12T18:35:03.286+0000] {standard_task_runner.py:57} INFO - Started process 55 to run task
[2024-07-12T18:35:03.288+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp76j4cz06']
[2024-07-12T18:35:03.289+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask s3_upload
[2024-07-12T18:35:03.305+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [running]> on host 0b36f00089aa
[2024-07-12T18:35:03.329+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T18:35:15.871+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-07-12T18:35:15.873+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-07-12T18:35:15.888+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20240711T000000, start_date=20240712T183503, end_date=20240712T183515
[2024-07-12T18:35:15.898+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task s3_upload ('NoneType' object has no attribute 'split'; 55)
[2024-07-12T18:35:15.932+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-12T18:35:15.945+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T18:51:40.185+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:51:40.189+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:51:40.189+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-12T18:51:40.194+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-07-11 00:00:00+00:00
[2024-07-12T18:51:40.196+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2024-07-12T18:51:40.198+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpyvf1ln_e']
[2024-07-12T18:51:40.200+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask s3_upload
[2024-07-12T18:51:40.218+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [running]> on host a6a45b354d90
[2024-07-12T18:51:40.245+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T18:51:51.967+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-07-12T18:51:51.970+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-07-12T18:51:51.981+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20240711T000000, start_date=20240712T185140, end_date=20240712T185151
[2024-07-12T18:51:51.991+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task s3_upload ('NoneType' object has no attribute 'split'; 60)
[2024-07-12T18:51:51.999+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-12T18:51:52.008+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T19:03:37.535+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T19:03:37.539+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T19:03:37.539+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-12T19:03:37.543+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-07-11 00:00:00+00:00
[2024-07-12T19:03:37.545+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2024-07-12T19:03:37.547+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp2fpqdkx0']
[2024-07-12T19:03:37.548+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask s3_upload
[2024-07-12T19:03:37.567+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [running]> on host 812eeef3f95b
[2024-07-12T19:03:37.592+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T19:03:37.788+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-07-12T19:03:37.789+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-07-12T19:03:37.794+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20240711T000000, start_date=20240712T190337, end_date=20240712T190337
[2024-07-12T19:03:37.800+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task s3_upload ('NoneType' object has no attribute 'split'; 62)
[2024-07-12T19:03:37.814+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-12T19:03:37.823+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T19:28:34.002+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T19:28:34.006+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T19:28:34.006+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-12T19:28:34.010+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-07-11 00:00:00+00:00
[2024-07-12T19:28:34.012+0000] {standard_task_runner.py:57} INFO - Started process 54 to run task
[2024-07-12T19:28:34.014+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp2gwfn7rk']
[2024-07-12T19:28:34.015+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask s3_upload
[2024-07-12T19:28:34.032+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-07-11T00:00:00+00:00 [running]> on host 4928c5b9e5ae
[2024-07-12T19:28:34.056+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T19:28:34.316+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-07-12T19:28:34.686+0000] {logging_mixin.py:151} INFO - File uploaded to s3
[2024-07-12T19:28:34.687+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-12T19:28:34.699+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20240711T000000, start_date=20240712T192834, end_date=20240712T192834
[2024-07-12T19:28:34.735+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-12T19:28:34.746+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
